// Central data: services & cities for Aanya Home Healthcare

export const SERVICES = [
  { slug: 'home-nursing', name: 'Home Nursing', icon: 'Stethoscope', short: '24/7 professional nursing at your doorstep.', description: 'Trained RNs & GNMs delivering hospital-grade nursing care at home — IV therapy, wound care, catheter care, vital monitoring & post-op recovery.', includes: ['Wound & dressing care', 'IV cannulation & medication', 'Vital signs monitoring', 'Catheter/Ryles tube care', 'Post-operative care', 'Doctor coordination'], startingPrice: 800, unit: 'shift (12h)' },
  { slug: 'caregiver-services', name: 'Caregiver Services', icon: 'HandHeart', short: 'Compassionate long-term caregivers.', description: 'Trained, background-verified caregivers for daily support: hygiene, feeding, mobility, and companionship for the elderly & bedridden.', includes: ['Personal hygiene support', 'Meal assistance & feeding', 'Mobility & transfer help', 'Medication reminders', 'Companionship', 'Bed sore prevention'], startingPrice: 700, unit: 'shift (12h)' },
  { slug: 'elder-care', name: 'Elder Care', icon: 'Users', short: 'Dignified senior care at home.', description: 'Holistic elderly care combining medical supervision, physiotherapy, nutrition & emotional wellbeing.', includes: ['Geriatric doctor visits', 'Fall risk assessment', 'Physio & mobility', 'Nutrition planning', 'Family reporting'], startingPrice: 900, unit: 'day' },
  { slug: 'patient-attendant', name: 'Patient Attendant', icon: 'ShieldPlus', short: 'Reliable daily attendants.', description: 'Trained non-medical attendants supporting daily patient needs in home or hospital settings.', includes: ['Feeding & hydration', 'Bathing & grooming', 'Toileting assistance', 'Ambulation support', 'Basic vitals'], startingPrice: 650, unit: 'shift (12h)' },
  { slug: 'icu-setup-at-home', name: 'ICU Setup at Home', icon: 'Activity', short: 'Full ICU care in your bedroom.', description: 'Complete home-ICU: ventilator, cardiac monitor, oxygen, suction & round-the-clock critical care nurses.', includes: ['Ventilator support', 'Cardiac monitoring', 'BiPAP / CPAP', 'Critical care nurse 24x7', 'ICU consultant tele-rounds'], startingPrice: 4500, unit: 'day' },
  { slug: 'physiotherapy', name: 'Physiotherapy at Home', icon: 'Wheelchair', short: 'Recovery & rehab at home.', description: 'Certified physiotherapists for post-surgery rehab, stroke recovery, orthopaedic and neurological conditions.', includes: ['Orthopaedic rehab', 'Neuro rehab', 'Post-op mobilisation', 'Chest physio', 'Pain management'], startingPrice: 600, unit: 'session' },
  { slug: 'doctor-at-home', name: 'Doctor at Home', icon: 'Stethoscope', short: 'MBBS & specialist visits.', description: 'Verified physicians visit your home for consultation, chronic care review and prescriptions.', includes: ['General physician visit', 'Specialist consultation', 'Prescription & advice', 'Chronic disease review'], startingPrice: 999, unit: 'visit' },
  { slug: 'injection-dressing', name: 'Injection & Dressing', icon: 'Syringe', short: 'On-demand nurse visits.', description: 'Quick nurse visits for injections, IM/IV shots, wound dressing, and suture removal.', includes: ['IM / IV / SC injections', 'Wound cleaning & dressing', 'Suture removal', 'Post-op site care'], startingPrice: 299, unit: 'visit' },
  { slug: 'tracheostomy-care', name: 'Tracheostomy Care', icon: 'Wind', short: 'Skilled trach care.', description: 'Specialised nurses trained in tracheostomy suction, tube change and infection prevention.', includes: ['Trach suctioning', 'Tube change', 'Stoma care', 'Humidification', 'Emergency handling'], startingPrice: 1200, unit: 'shift' },
  { slug: 'stroke-care', name: 'Stroke Care', icon: 'Brain', short: 'Post-stroke rehab program.', description: 'Multidisciplinary post-stroke rehab: neuro-physio, speech therapy, nursing and family training.', includes: ['Neuro-physiotherapy', 'Speech therapy', 'Swallow assessment', 'Home safety audit'], startingPrice: 1500, unit: 'day' },
  { slug: 'dementia-care', name: 'Dementia Care', icon: 'Brain', short: 'Structured dementia support.', description: 'Behaviour-trained caregivers with structured routines, safety-proofing and cognitive activities.', includes: ['Behaviour-trained caregiver', 'Cognitive activities', 'Safety proofing', 'Family counselling'], startingPrice: 1100, unit: 'day' },
  { slug: 'alzheimers-care', name: "Alzheimer's Care", icon: 'Brain', short: 'Specialised memory care.', description: 'Compassionate, patient-first Alzheimer\u2019s care with memory-support activities and 24x7 supervision.', includes: ['Memory-support routines', '24x7 supervision', 'Nutrition support', 'Family reporting'], startingPrice: 1200, unit: 'day' },
  { slug: 'parkinsons-care', name: "Parkinson's Care", icon: 'Sparkles', short: 'Movement disorder care.', description: 'Parkinson\u2019s-focused physio, medication scheduling and fall-prevention support.', includes: ['Parkinson-specific physio', 'Medication scheduling', 'Fall prevention', 'Swallow safety'], startingPrice: 1100, unit: 'day' },
  { slug: 'cancer-care', name: 'Cancer Care', icon: 'Ribbon', short: 'Oncology home care.', description: 'Home chemo support, port care, pain management and emotional support during cancer treatment.', includes: ['Chemo port care', 'Nausea & pain mgmt', 'Nutrition support', 'Emotional counselling'], startingPrice: 1800, unit: 'day' },
  { slug: 'palliative-care', name: 'Palliative Care', icon: 'HeartPulse', short: 'Comfort & dignity focused care.', description: 'End-of-life care focused on comfort, symptom relief and family support.', includes: ['Symptom & pain relief', 'Comfort nursing', 'Family bereavement support', 'Spiritual care coordination'], startingPrice: 2000, unit: 'day' },
  { slug: 'mother-baby-care', name: 'Mother & Baby Care', icon: 'Baby', short: 'Postnatal & newborn care.', description: 'Certified postnatal caregivers for new mothers and infants \u2014 lactation, hygiene, sleep training.', includes: ['Newborn bathing & massage', 'Lactation support', 'Postnatal recovery', 'Night care'], startingPrice: 1500, unit: 'day' },
  { slug: 'medical-equipment-rental', name: 'Medical Equipment Rental', icon: 'Bed', short: 'Beds, oxygen, monitors on rent.', description: 'Sanitised medical equipment on rent \u2014 hospital beds, oxygen concentrators, wheelchairs, BiPAP, suction.', includes: ['Hospital beds', 'Oxygen concentrators', 'BiPAP / CPAP', 'Wheelchairs', 'Suction machines'], startingPrice: 150, unit: 'day' },
];

export const CITIES = [
  { slug: 'pune', name: 'Pune', state: 'Maharashtra', tagline: 'Home healthcare across Pune & PCMC.', population: '7.4M+', areas: ['Kothrud','Baner','Viman Nagar','Hinjewadi','Kharadi','Wakad','Aundh','Camp'] },
  { slug: 'mumbai', name: 'Mumbai', state: 'Maharashtra', tagline: 'Trusted care across Greater Mumbai.', population: '20M+', areas: ['Andheri','Bandra','Powai','Thane','Navi Mumbai','Borivali','Malad','Dadar'] },
  { slug: 'bangalore', name: 'Bangalore', state: 'Karnataka', tagline: 'Bengaluru\u2019s premium home care.', population: '13M+', areas: ['Whitefield','Koramangala','Indiranagar','HSR Layout','Electronic City','JP Nagar','Marathahalli','Jayanagar'] },
  { slug: 'hyderabad', name: 'Hyderabad', state: 'Telangana', tagline: 'Care that reaches every zone.', population: '10M+', areas: ['Gachibowli','Madhapur','Banjara Hills','Jubilee Hills','Kukatpally','Hitech City','Secunderabad','Miyapur'] },
  { slug: 'delhi', name: 'Delhi NCR', state: 'Delhi', tagline: 'Delhi, Gurugram, Noida & Faridabad.', population: '30M+', areas: ['Gurugram','Noida','Dwarka','Rohini','Saket','South Ex','Faridabad','Ghaziabad'] },
  { slug: 'kolkata', name: 'Kolkata', state: 'West Bengal', tagline: 'Compassionate care in Kolkata.', population: '15M+', areas: ['Salt Lake','New Town','Ballygunge','Park Street','Jadavpur','Behala','Howrah','Rajarhat'] },
  { slug: 'ranchi', name: 'Ranchi', state: 'Jharkhand', tagline: 'Ranchi\u2019s trusted home care.', population: '1.5M+', areas: ['Kanke','Doranda','Lalpur','Hinoo','Bariatu','Ratu Road','Booty More','Harmu'] },
  { slug: 'bhubaneswar', name: 'Bhubaneswar', state: 'Odisha', tagline: 'Odisha\u2019s smart-city home care.', population: '1.2M+', areas: ['Chandrasekharpur','Patia','Nayapalli','Saheed Nagar','Jaydev Vihar','Kalinga Nagar','Khandagiri','Sundarpada'] },
];

export const TESTIMONIALS = [
  { name: 'Priya Sharma', city: 'Pune', text: 'The ICU-at-home setup for my father was flawless. Kind nurses, quick response and doctors on call. Truly life-saving.', rating: 5 },
  { name: 'Rahul Verma', city: 'Bangalore', text: 'Post-surgery physiotherapy at home helped my mother walk again within 3 weeks. Highly recommended.', rating: 5 },
  { name: 'Anita Das', city: 'Kolkata', text: 'Compassionate caregiver for my grandmother with dementia. She treats her like family.', rating: 5 },
  { name: 'Suresh Nair', city: 'Mumbai', text: 'Booked a nurse for daily insulin \u2014 always on time, super professional. WhatsApp booking is so easy.', rating: 5 },
  { name: 'Meena Iyer', city: 'Hyderabad', text: 'Palliative care for my father in his last days was handled with unmatched dignity. Forever grateful.', rating: 5 },
  { name: 'Amit Singh', city: 'Delhi NCR', text: 'Mother & baby care after my wife\u2019s C-section was a blessing. Trained, hygienic, and warm.', rating: 5 },
];

export const FAQS = [
  { q: 'Are your nurses & caregivers verified?', a: 'Yes. Every professional undergoes background verification, credential validation and on-boarding training including infection control & patient safety.' },
  { q: 'How quickly can care begin?', a: 'Most services (nurse visits, attendants, physio) can start within 2\u20134 hours in metro cities. ICU-at-home setup typically starts within 6\u201312 hours.' },
  { q: 'Do you accept insurance / reimbursement?', a: 'We provide detailed invoices and clinical documentation accepted by all major TPAs for reimbursement claims.' },
  { q: 'Can I change my caregiver if not satisfied?', a: 'Absolutely. Free replacement within 24 hours, no questions asked.' },
  { q: 'Do you serve tier-2 cities?', a: 'Yes \u2014 we operate in Pune, Mumbai, Bangalore, Hyderabad, Delhi NCR, Kolkata, Ranchi and Bhubaneswar with expanding coverage.' },
  { q: 'What if there\u2019s a medical emergency?', a: 'Every case has a nursing supervisor & doctor-on-call. We coordinate ambulance and hospital admission if required.' },
];
